### ISSUE TITLE
Building up environments

### ISSUE THREAD

**Issue by Neal2020GitHub** [bdaiinstitute/vlfm#25]
Hi authors! Thanks for open-sourcing your work! 

I'm wondering if there's a requirements.txt file (or etc) to help us build up the environments. Many Thanks!

**Comment by jiuguangw** [comment]
You probably figured it out but `pyproject.toml` is the place for storing dependencies for modern Python. You can do `pip install -e .[habitat]`, which pulls from the list within `pyproject.toml`.

**Comment by Neal2020GitHub** [comment]
Yes, thank you. By the way, the original issue I encounterd was that we need to use `'.[habitat]'` instead of `.[habitat]` in zsh.

**Comment by jiuguangw** [comment]
Ah yes,  you can also escape with `.\[whatever\]`
