### ISSUE TITLE
How to visualize the exploration process including the environment, robot, target and planned path?

### ISSUE THREAD

**Issue by DrDengDi** [bdaiinstitute/vlfm#26]
After running 
```
python -m vlfm.run 
```
The terminal shows this error: 
```
AttributesManagerBase.h(357)::buildAttrSrcPathsFromJSONAndLoad : No Glob path result for ./data/scene_datasets/hm3d_v0.2/val/00891-cvZr5TUy5C5/.basis.scene_instance.json
[16:11:54:313870]:[Metadata] AttributesManagerBase.h(357)::buildAttrSrcPathsFromJSONAndLoad : No Glob path result for ./data/scene_datasets/hm3d_v0.2/val/00894-HY1NcmCgn3n/.basis.scene_instance.json
```
and 
![image](https://github.com/bdaiinstitute/vlfm/assets/162066519/ff6353ef-ff48-45b7-ae54-51474e34779e)

How to solve this error?
May I know **how to get the visualization of the environment, robot and path** as shown in the README's figure, i.e., what commands to run?
![image](https://github.com/bdaiinstitute/vlfm/assets/162066519/10e51fa2-c777-485f-9997-34c600593c6c)

### inconsistent file name

HM3D_OBJECTNAV is defined as objectnav_hm3d_v2.zip,  but unzip objectnav_hm3d_v1 file and the folder name is $DATA_DIR/datasets/objectnav/hm3d/v1

```
HM3D_OBJECTNAV=https://dl.fbaipublicfiles.com/habitat/data/datasets/objectnav/hm3d/v2/objectnav_hm3d_v2.zip
wget $HM3D_OBJECTNAV &&
unzip objectnav_hm3d_v1.zip &&
mkdir -p $DATA_DIR/datasets/objectnav/hm3d  &&
mv objectnav_hm3d_v1 $DATA_DIR/datasets/objectnav/hm3d/v1 &&
rm objectnav_hm3d_v1.zip
```
**solution**: change HM3D_OBJECTNAV from v2 to v1 or change the unzip file and folder to v2 and update the predefined data file to v2 and update the hardcoded data/datasets/objectnav/hm3d/v1/{split}/{split}.json.gz to v2.

### No instruction to run server

Connection error after running 

```jsx
python -m vlfm.run
```

HTTPConnectionPool(host='localhost', port=12182): Max retries exceeded with url: /blip2itm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75083089c8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**solution**: run 

```jsx
./scripts/launch_vlm_servers.sh
```
before 
```jsx
python -m vlfm.run
```

**Comment by Neal2020GitHub** [comment]
Hi, 

When I run  `python -m vlfm.run`, it raises "FileNotFoundError: Could not find dataset file `data/datasets/objectnav/hm3d/v1/val`".  

Have you encountered such issue? 

Cheers!

**Comment by Neal2020GitHub** [comment]
Hi @DrDengDi,

When I run python -m vlfm.run, it raises "FileNotFoundError: Could not find dataset file data/datasets/objectnav/hm3d/v1/val".

Have you encountered such issue? It seems that the data is stored at the correct location. 

Cheers!

**Comment by DrDengDi** [comment]
Hi @Neal2020GitHub To solve this issue, I ran the debugger from vlfm/run.py and added a breakpoint at ~/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py as shown in the image to check what is difference between the data_path and the stored file path.
![image](https://github.com/bdaiinstitute/vlfm/assets/162066519/ef397d92-b122-49f0-8ebd-9fb4ee1b693f)

**Comment by DrDengDi** [comment]
@naokiyokoyama Could you tell me how to get the visualization of the environment, robot and path as shown in the README's figure, i.e., what commands to run?

**Comment by Neal2020GitHub** [comment]
Hi @DrDengDi,

I ran the debugger an it seemed that `os.path.exists(config.scenes_dir)` is Flase here. I am wondering what should be stored in `scenes_dir` or just to create an empty directory? 

Cheers!

**Comment by Neal2020GitHub** [comment]
Hi @DrDengDi,

I ran the debugger an it seemed that `os.path.exists(config.scenes_dir)` is False here. I am wondering what should be stored in `scenes_dir` or just to create an empty directory?

Cheers!

**Comment by Neal2020GitHub** [comment]
> Hi @Neal2020GitHub To solve this issue, I ran the debugger from vlfm/run.py and added a breakpoint at ~/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py as shown in the image to check what is difference between the data_path and the stored file path. ![image](https://private-user-images.githubusercontent.com/162066519/316268191-ef397d92-b122-49f0-8ebd-9fb4ee1b693f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjk5ODIsIm5iZiI6MTcxMTMyOTY4MiwicGF0aCI6Ii8xNjIwNjY1MTkvMzE2MjY4MTkxLWVmMzk3ZDkyLWIxMjItNDlmMC04ZWJkLTlmYjRlZTFiNjkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMTIxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjQ1YmVlOWMwN2Q2ZGU2NzQ3OWE3OWVlMDNkZGIxN2EzODI5YjgwZTJiYWIxYTA3MWIzMTc0OTI4YmFhNDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xv2XYFQVgKOmRRlb7eqyKUMvWQ3DjT46Wuol0dHiORk)

Thank you! It works now.

**Comment by naokiyokoyama** [comment]
@DrDengDi to generate the videos, you will need to add "disk" to `habitat_baselines.eval.video_option` (`"['disk']"`)

You will also need to set `habitat_baselines.video_dir` to a directory of your choosing. It will be created if it does not exist.

What will be visualized is the ground truth shortest path (green), the agent's trajectory so far (blue), and locations of goal object instances (red).

More config options for habitat_baselines can be found here: https://github.com/facebookresearch/habitat-lab/blob/main/habitat-baselines/habitat_baselines/config/default_structured_configs.py

**Comment by naokiyokoyama** [comment]
@DrDengDi Regarding the 'error' that you posted, I believe that you can ignore that. I have also updated the README per your suggestions, thank you.

**Comment by Neal2020GitHub** [comment]
When I tried to generate videos, it raised `TypeError: unsupported format string passed to numpy.ndarray.__format__`.

<img width="1145" alt="image" src="https://github.com/bdaiinstitute/vlfm/assets/70187327/62878293-b671-4d06-8b7d-5611b69d7904">

Any solutions about it? Thanks!

**Comment by naokiyokoyama** [comment]
I have pushed a fix in `d79d7f1d7e047f34e048f61ce34ad85379dbaa7c`, thanks for pointing it out.

**Comment by PEACHTTT** [comment]
> > Hi @Neal2020GitHub To solve this issue, I ran the debugger from vlfm/run.py and added a breakpoint at ~/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py as shown in the image to check what is difference between the data_path and the stored file path. <img alt="image" width="37.94999694824219" height="15" src="https://private-user-images.githubusercontent.com/162066519/316268191-ef397d92-b122-49f0-8ebd-9fb4ee1b693f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjk5ODIsIm5iZiI6MTcxMTMyOTY4MiwicGF0aCI6Ii8xNjIwNjY1MTkvMzE2MjY4MTkxLWVmMzk3ZDkyLWIxMjItNDlmMC04ZWJkLTlmYjRlZTFiNjkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMTIxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjQ1YmVlOWMwN2Q2ZGU2NzQ3OWE3OWVlMDNkZGIxN2EzODI5YjgwZTJiYWIxYTA3MWIzMTc0OTI4YmFhNDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xv2XYFQVgKOmRRlb7eqyKUMvWQ3DjT46Wuol0dHiORk">嗨，为了解决这个问题，我从 vlfm/run.py 运行调试器，并在 ~/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py 处添加了一个断点，如图所示，以检查data_path和存储的文件路径之间的区别。 <img alt="image" width="37.94999694824219" height="15" src="https://private-user-images.githubusercontent.com/162066519/316268191-ef397d92-b122-49f0-8ebd-9fb4ee1b693f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjk5ODIsIm5iZiI6MTcxMTMyOTY4MiwicGF0aCI6Ii8xNjIwNjY1MTkvMzE2MjY4MTkxLWVmMzk3ZDkyLWIxMjItNDlmMC04ZWJkLTlmYjRlZTFiNjkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMTIxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjQ1YmVlOWMwN2Q2ZGU2NzQ3OWE3OWVlMDNkZGIxN2EzODI5YjgwZTJiYWIxYTA3MWIzMTc0OTI4YmFhNDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xv2XYFQVgKOmRRlb7eqyKUMvWQ3DjT46Wuol0dHiORk">
> 
> Thank you! It works now.谢谢！它现在起作用了。

![图片](https://github.com/bdaiinstitute/vlfm/assets/66247791/11c1f391-a6c6-4b2b-90f9-5c70adf3e9d5)
hello,I have this problem too "Could not find dataset file data/datasets/objectnav/hm3d/v1/val" AND after trying check point, and this is the error measures. How can I fix this?

**Comment by PEACHTTT** [comment]
> After running 运行后
> 
> ```
> python -m vlfm.run 
> ```
> 
> The terminal shows this error:终端显示以下错误：
> 
> ```
> AttributesManagerBase.h(357)::buildAttrSrcPathsFromJSONAndLoad : No Glob path result for ./data/scene_datasets/hm3d_v0.2/val/00891-cvZr5TUy5C5/.basis.scene_instance.json
> [16:11:54:313870]:[Metadata] AttributesManagerBase.h(357)::buildAttrSrcPathsFromJSONAndLoad : No Glob path result for ./data/scene_datasets/hm3d_v0.2/val/00894-HY1NcmCgn3n/.basis.scene_instance.json
> ```
> 
> and 和 ![image](https://private-user-images.githubusercontent.com/162066519/313344464-ff6353ef-ff48-45b7-ae54-51474e34779e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjcxOTAsIm5iZiI6MTcyMDE2Njg5MCwicGF0aCI6Ii8xNjIwNjY1MTkvMzEzMzQ0NDY0LWZmNjM1M2VmLWZmNDgtNDViNy1hZTU0LTUxNDc0ZTM0Nzc5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwODA4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGM2ZjI2Y2ZhNTg3ZjA2NjE3MWZkYjlmMTkyMjczMTdhMWI0YzJhZmQ1Y2MwOGViOTMyMDVlMTdlM2FhYzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ULkv3YKyHLtyvMYnOG2n930Ld-zLKb182En4lMEYcEk)
> 
> How to solve this error?如何解决这个错误？ May I know **how to get the visualization of the environment, robot and path** as shown in the README's figure, i.e., what commands to run?我是否可以知道如何获得 README 图中所示的环境、机器人和路径的可视化，即要运行哪些命令？ ![image](https://private-user-images.githubusercontent.com/162066519/313344583-10e51fa2-c777-485f-9997-34c600593c6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjcxOTAsIm5iZiI6MTcyMDE2Njg5MCwicGF0aCI6Ii8xNjIwNjY1MTkvMzEzMzQ0NTgzLTEwZTUxZmEyLWM3NzctNDg1Zi05OTk3LTM0YzYwMDU5M2M2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwODA4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTlkNGUzNDQ1Zjg0NTBmMTAwYmY5MzcxMjRlMjMwMjNlM2VkYmIyN2MwMzhlYzk3ZGEyYTk5OWVlZWZkN2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pEiwkeF9IQEUzDZeO4Ts7lymoS0S7z2HG5PPqIUFzDg)
> ## Minor comments in the README
> 自述文件中的小注释
> ### inconsistent file name 文件名不一致
> 
> HM3D_OBJECTNAV is defined as objectnav_hm3d_v2.zip, but unzip objectnav_hm3d_v1 file and the folder name is $DATA_DIR/datasets/objectnav/hm3d/v1HM3D_OBJECTNAV定义为objectnav_hm3d_v2.zip，但解压缩objectnav_hm3d_v1文件，文件夹名称为 $DATA_DIR/datasets/objectnav/hm3d/v1
> 
> ```
> HM3D_OBJECTNAV=https://dl.fbaipublicfiles.com/habitat/data/datasets/objectnav/hm3d/v2/objectnav_hm3d_v2.zip
> wget $HM3D_OBJECTNAV &&
> unzip objectnav_hm3d_v1.zip &&
> mkdir -p $DATA_DIR/datasets/objectnav/hm3d  &&
> mv objectnav_hm3d_v1 $DATA_DIR/datasets/objectnav/hm3d/v1 &&
> rm objectnav_hm3d_v1.zip
> ```
> 
> **solution**: change HM3D_OBJECTNAV from v2 to v1 or change the unzip file and folder to v2 and update the predefined data file to v2 and update the hardcoded data/datasets/objectnav/hm3d/v1/{split}/{split}.json.gz to v2.解决方案：将HM3D_OBJECTNAV从 V2 更改为 V1，或将解压缩文件和文件夹更改为 V2，将预定义数据文件更新为 V2，并将硬编码的 data/datasets/objectnav/hm3d/v1/{split}/{split}.json.gz 更新为 v2。
> ### No instruction to run server
> 没有运行服务器的指令
> 
> Connection error after running运行后出现连接错误
> 
> ```js
> python -m vlfm.run
> ```
> 
> HTTPConnectionPool(host='localhost', port=12182): Max retries exceeded with url: /blip2itm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75083089c8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))HTTPConnectionPool（host='localhost'， port=12182）： 超出最大重试次数 url： /blip2itm （由 NewConnectionError（'<urllib3.connection.HTTPConnection 对象在 0x75083089c8e0>： 无法建立新连接： [Errno 111] 连接被拒绝'））
> 
> **solution**: run 解决方案：运行
> 
> ```js
> ./scripts/launch_vlm_servers.sh
> ```
> 
> before 以前
> 
> ```js
> python -m vlfm.run
> ```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'magnum.scenegraph'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tcy/vlfm-main/vlfm/run.py", line 11, in <module>
    import frontier_exploration  # noqa
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/frontier_exploration/__init__.py", line 3, in <module>
    import frontier_exploration.base_explorer
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/frontier_exploration/base_explorer.py", line 5, in <module>
    import habitat_sim
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/__init__.py", line 13, in <module>
    import habitat_sim._ext.habitat_sim_bindings
ImportError: initialization failed

####
Hi,When I run python -m vlfm.run, it raises issues above, I have install magnum 18.0.0.Could you tell me how to fix this ?

**Comment by PEACHTTT** [comment]
@[DrDengDi](https://github.com/DrDengDi)
Hi,when I run python -m vlfm.run, it raises issues below.Could you tell me how to fix this ?

######
The total is Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'magnum.scenegraph'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tcy/vlfm-main/vlfm/run.py", line 11, in <module>
    import frontier_exploration  # noqa
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/frontier_exploration/__init__.py", line 3, in <module>
    import frontier_exploration.base_explorer
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/frontier_exploration/base_explorer.py", line 5, in <module>
    import habitat_sim
  File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/__init__.py", line 13, in <module>
    import habitat_sim._ext.habitat_sim_bindings
ImportError: initialization failed
