### ISSUE TITLE
workshop paper to cof paper

### ISSUE THREAD

**Issue by DoongLi** [bdaiinstitute/vlfm#30]
I have a question. I have no other intention. Is it reasonable to transfer the workshop paper directly to the other coference？

**Comment by LebinLiang** [comment]
你好！想问问你是否也在关注这个项目，我正在尝试复现这个项目，希望能一起讨论其中细节。我之前也参加RoboMaster比赛，参与哨兵研发，SLAM和导航方向

**Comment by DoongLi** [comment]
Hi, you can tell me your WeChat via the email(lidong8421bcd@gmail.com)~
