### ISSUE TITLE
Text prompt

### ISSUE THREAD

**Issue by DoongLi** [bdaiinstitute/vlfm#31]
Hi, congratulations to this paper for winning ICRA awards. I have a question about Text prompt, is it generated by BLIP-2 or artificially?

**Comment by DoongLi** [comment]
like：Text prompt: "Seems like there's a microwave ahead."

**Comment by naokiyokoyama** [comment]
The prompt is a fixed template, meaning it should always just be "Seems like there's a ___ ahead." but the blank is replaced with the target object category. It could be altered to use a different prompt template, but we have found this one to work well.

**Comment by DoongLi** [comment]
I got it, thx!
