### ISSUE TITLE
ImportError: generic_type: type "SceneNode" referenced unknown base type "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicTranslationRotationScalingTransformation3D<float> >"

### ISSUE THREAD

**Issue by PEACHTTT** [bdaiinstitute/vlfm#34]
After models being loaded,I run the **"python -m vlfm.run"**.
Then comes the PROBLEM that:

![图片](https://github.com/bdaiinstitute/vlfm/assets/66247791/e347738c-9872-4b1f-95aa-cdf3020bdd44)
Could you tell me how to fix this?

**Comment by ayushzenith** [comment]
I had the same error. Cloning and installing habitat-lab fixed it

**Comment by Roberyan** [comment]
@ayushzenith 
Do you mean git clone habitat-lab github repo under vlfm repo？I am confused with the installation that I follow the toml content and installed habitat without cloning it, this is the wrong installation?

**Comment by ayushzenith** [comment]
@Roberyan This is my fork of this library. Give the installation instructions in the README.md a try. It worked for me!
