### ISSUE TITLE
Problems about running "python -m vlfm.run"

### ISSUE THREAD

**Issue by Benson722** [bdaiinstitute/vlfm#35]
Thank you for your work! It helps me a lot. :-)

When I try to run the code, some errors occur:

```
(vlfm) zhangyiqing@inin:~/vlfm$ python -m vlfm.run
Could not import yolov7. This is OK if you are only using the client.
In 'habitat_baselines/rl/policy/vlfm_policy': ValidationError raised while composing config:
Invalid type assigned: str is not a subclass of PolicyConfig. value: HabitatITMPolicy
    full_key: habitat_baselines.rl.policy.name
    reference_type=Dict[str, PolicyConfig]
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

ps: "./scripts/launch_vlm_servers.sh" is running successfully

**Comment by imfks** [comment]
Maybe u can try cloning the habitat in --branch v0.2.4 ? Not the stable one.

**Comment by PEACHTTT** [comment]
Just run **pip install -e .[habitat]**, make sure the version(habitat-sim,habitat-lab) is correct, you can check the file pyproject.toml.Please let me know if the problem is correct, I have  some questions that I would like to discuss with you. Thanks!

**Comment by PEACHTTT** [comment]
> Maybe u can try cloning the habitat in --branch v0.2.4 ? Not the stable one.

Hi,I wonder if you met the problem that   
**File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py", line 51, in get_scenes_to_load
    raise FileNotFoundError(
FileNotFoundError: Could not find dataset file `data/datasets/objectnav/hm3d/v1/val`**

I'm sure the datasets is in /home /name/vlfm/data/datasets/objectnav/hm3d/v1/val`

**Comment by Benson722** [comment]
> > Maybe u can try cloning the habitat in --branch v0.2.4 ? Not the stable one.
> 
> Hi,I wonder if you met the problem that **File "/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py", line 51, in get_scenes_to_load raise FileNotFoundError( FileNotFoundError: Could not find dataset file `data/datasets/objectnav/hm3d/v1/val`**
> 
> I'm sure the datasets is in /home /name/vlfm/data/datasets/objectnav/hm3d/v1/val`

Sorry for replying late. I have not met this problem. It seems like a problem about the dataset locations. Perhaps you can try download the dataset by the recommended ways again. Hope it works. :)

**Comment by Benson722** [comment]
The problem has been solved by being installed again. Perhaps some errors occur in the environment

**Comment by knightwzh** [comment]
I have met the same problem and here is how I solved it.
The error is raised in line 51 in "habitat/datasets/pointnav/pointnav_dataset.py", which is triggered when cls.check_config_paths_exist(config) returns true. And cls.check_config_paths_exist(config) actually checks both the dir "/name/vlfm/data/datasets/objectnav/hm3d/v1/val" and another dir "/name/vlfm/data/scene_datasets" where the glb and navmesh files of mp3d are stored.
So you need to check if the BOTH dir is existed.

**Comment by feihuafuyou** [comment]
> > 也许你可以尝试克隆 --branch v0.2.4 中的habitat？不是稳定版。
> 
> 你好，我想知道你是否遇到了文件 **“/home/tcy/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py”, 第 51 行, 在 get_scenes_to_load 中 引发 FileNotFoundError( FileNotFoundError: 找不到数据集文件`data/datasets/objectnav/hm3d/v1/val`**
> 
> 我确定数据集位于 /home /name/vlfm/data/datasets/objectnav/hm3d/v1/val`

Hi，I have also encountered this problem. Have you solved it? Thanks!

![Image](https://github.com/user-attachments/assets/826aab54-7b09-4e7b-a01d-c262b7d9668a)

**Comment by luohongk** [comment]
I have same problem

**Comment by Leon12334** [comment]
I have this problem,too. Have you solved it? Thanks

**Comment by luohongk** [comment]
I have solved it

**Comment by feihuafuyou** [comment]
> I have solved it

Sorry, I planned to reply to you today, but I forgot. It was indeed an issue with the dataset. Firstly, we need to ensure the integrity of the dataset, and secondly, the location of the dataset. I think the readme was a bit vague, but it was ultimately resolved.

**Comment by feihuafuyou** [comment]
> I have this problem,too. Have you solved it? Thanks

Hey,I have solved this problem. Firstly, it is necessary to ensure the integrity of the dataset, and secondly, it is necessary to ensure that the path of the dataset is correct.
![Image](https://github.com/user-attachments/assets/9dfbd4df-da98-4ba5-935c-dfd191f727eb)
![Image](https://github.com/user-attachments/assets/6ffd22d1-bd05-4659-bf7a-06dc739e691b)
![Image](https://github.com/user-attachments/assets/91de06e8-0000-45c4-aac4-8321a74d0907)
![Image](https://github.com/user-attachments/assets/9f4520eb-f2f7-4c2e-ac61-08dfe667b947)

**Comment by luohongk** [comment]
> > I have this problem,too. Have you solved it? Thanks
> 
> Hey,I have solved this problem. Firstly, it is necessary to ensure the integrity of the dataset, and secondly, it is necessary to ensure that the path of the dataset is correct. ![Image](https://github.com/user-attachments/assets/9dfbd4df-da98-4ba5-935c-dfd191f727eb) ![Image](https://github.com/user-attachments/assets/6ffd22d1-bd05-4659-bf7a-06dc739e691b) ![Image](https://github.com/user-attachments/assets/91de06e8-0000-45c4-aac4-8321a74d0907) ![Image](https://github.com/user-attachments/assets/9f4520eb-f2f7-4c2e-ac61-08dfe667b947)

wonderful，but i have another problem,https://github.com/bdaiinstitute/vlfm/issues/81.Can you help me?

**Comment by Leon12334** [comment]
> > > 我也遇到了这个问题。你解决了吗？谢谢
> > 
> > 
> > 嘿嘿，这个问题我已经解决了，首先要保证数据集的完整性，其次要保证数据集的路径正确。![Image](https://github.com/user-attachments/assets/9dfbd4df-da98-4ba5-935c-dfd191f727eb) ![图像](https://private-user-images.githubusercontent.com/136301478/435469937-6ffd22d1-bd05-4659-bf7a-06dc739e691b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUxNTg1MzcsIm5iZiI6MTc0NTE1ODIzNywicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM3LTZmZmQyMmQxLWJkMDUtNDY1OS1iZjdhLTA2ZGM3MzllNjkxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQyMFQxNDEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDhmYmNjMGI2N2RlZjkwNzkxYjNhYzBlM2UxYmIxYWYyMTU2Y2Y2Y2Q1ZTc0ZGE2OWYyYTllZTZlMWYxMzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HkjarSnqx0GsmfZq7aKmYL0f9Tx8KBtLTr2kdY4kAJg) ![图像](https://private-user-images.githubusercontent.com/136301478/435469938-91de06e8-0000-45c4-aac4-8321a74d0907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUxNTg1MzcsIm5iZiI6MTc0NTE1ODIzNywicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM4LTkxZGUwNmU4LTAwMDAtNDVjNC1hYWM0LTgzMjFhNzRkMDkwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQyMFQxNDEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTYxMGFiMTZmMWZlNWFjZDJjYTI1NWM2NTQyZDBjZDFhZTA0YWUwZmY3NjhkNmY5ZDliNmNmNmU1YTBhZWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gkB9L3DrwyXWTzwk3UUExx8wdrRXW7RmAtA6F1KM3nY) ![图像](https://private-user-images.githubusercontent.com/136301478/435469939-9f4520eb-f2f7-4c2e-ac61-08dfe667b947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUxNTg1MzcsIm5iZiI6MTc0NTE1ODIzNywicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM5LTlmNDUyMGViLWYyZjctNGMyZS1hYzYxLTA4ZGZlNjY3Yjk0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQyMFQxNDEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzdiMzFmMTkzYzJiMjljYmNhNTNkMWU5OGU3MjU2M2Y4YjNhYjY2YWYxMDcxMjkxMmM5NmNjM2JlYWZhYmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8gf6KyLOi0dkPdLn-3ynYBP5C6XnaSXreC2mMSQlrdk)
> 
> 太棒了，但我还有另一个问题，[#81](https://github.com/bdaiinstitute/vlfm/issues/81)你能帮助我吗？

sorry，i just start for a while,so your problem i can not answer u. but thanks for your help

**Comment by Zflying1** [comment]
> > I have this problem,too. Have you solved it? Thanks
> 
> Hey,I have solved this problem. Firstly, it is necessary to ensure the integrity of the dataset, and secondly, it is necessary to ensure that the path of the dataset is correct. ![Image](https://github.com/user-attachments/assets/9dfbd4df-da98-4ba5-935c-dfd191f727eb) ![Image](https://github.com/user-attachments/assets/6ffd22d1-bd05-4659-bf7a-06dc739e691b) ![Image](https://github.com/user-attachments/assets/91de06e8-0000-45c4-aac4-8321a74d0907) ![Image](https://github.com/user-attachments/assets/9f4520eb-f2f7-4c2e-ac61-08dfe667b947)

Hi! Could you tell me where I can download the versioned data? Is it the same as the scene_datasets?

**Comment by feihuafuyou** [comment]
Yes, it will be automatically processed after downloading.

**Comment by Zflying1** [comment]
> Yes, it will be automatically processed after downloading.

OH Thanks！

**Comment by xudong-web** [comment]
> > I have this problem,too. Have you solved it? Thanks
> 
> Hey,I have solved this problem. Firstly, it is necessary to ensure the integrity of the dataset, and secondly, it is necessary to ensure that the path of the dataset is correct. ![Image](https://github.com/user-attachments/assets/9dfbd4df-da98-4ba5-935c-dfd191f727eb) ![Image](https://github.com/user-attachments/assets/6ffd22d1-bd05-4659-bf7a-06dc739e691b) ![Image](https://github.com/user-attachments/assets/91de06e8-0000-45c4-aac4-8321a74d0907) ![Image](https://github.com/user-attachments/assets/9f4520eb-f2f7-4c2e-ac61-08dfe667b947)

i dont have this two json files ，can you tell me how to download，this is my e-mail 1491096801@qq.com

**Comment by feihuafuyou** [comment]
> > > I have this problem,too. Have you solved it? Thanks
> > 
> > 
> > Hey,I have solved this problem. Firstly, it is necessary to ensure the integrity of the dataset, and secondly, it is necessary to ensure that the path of the dataset is correct. ![Image](https://github.com/user-attachments/assets/9dfbd4df-da98-4ba5-935c-dfd191f727eb) ![Image](https://private-user-images.githubusercontent.com/136301478/435469937-6ffd22d1-bd05-4659-bf7a-06dc739e691b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NzA5MjAsIm5iZiI6MTc2NDY3MDYyMCwicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM3LTZmZmQyMmQxLWJkMDUtNDY1OS1iZjdhLTA2ZGM3MzllNjkxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMlQxMDE3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDE2OTMxYjc3MGU0MWRlNTYzN2IxOTYyOWI3NTk2ZGNlYzZlNjE2NzA2YzQ3YzM4MmZiYzRhNjNiNjI1NmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nYbGWgbGaOZZUE-S47OLruts1Aum8ZruegKs20btWgc) ![Image](https://private-user-images.githubusercontent.com/136301478/435469938-91de06e8-0000-45c4-aac4-8321a74d0907.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NzA5MjAsIm5iZiI6MTc2NDY3MDYyMCwicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM4LTkxZGUwNmU4LTAwMDAtNDVjNC1hYWM0LTgzMjFhNzRkMDkwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMlQxMDE3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGE1OGE3ZmM2ODU4YTlmMzdlNTVjYmE5MWMwMzQwMjQ4ZTZmNjk1ZTE4ZDZhMTM4YmU3Y2Y5NTAxMjdlOGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PKrjXR86uIP-tVuJALtPaeWPhWYjSDfEUuUFEkXcHM0) ![Image](https://private-user-images.githubusercontent.com/136301478/435469939-9f4520eb-f2f7-4c2e-ac61-08dfe667b947.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NzA5MjAsIm5iZiI6MTc2NDY3MDYyMCwicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM5LTlmNDUyMGViLWYyZjctNGMyZS1hYzYxLTA4ZGZlNjY3Yjk0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMlQxMDE3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjQzMzA0MjdkZjJhODA1ZTY0MGUxOGM3MzA3NWI5N2FhMzE1ODU2MjM4N2FjMThhZWZjMmUzYmUwMDYxMTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PyIQXlfwyTjR1bqRknOqU84txCcvuJ73UmwC9WQggr8)
> 
> i dont have this two json files ，can you tell me how to download，this is my e-mail [1491096801@qq.com](mailto:1491096801@qq.com)

OK，Please wait for me to upload the dataset to Baidu Netdisk. If the upload is successful, I will then upload the dataset download link in this comment section.

**Comment by feihuafuyou** [comment]
Is there any interruption during the download process? The dataset is indeed too large, and I am not sure if uploading the dataset to Baidu Cloud is legal.

**Comment by feihuafuyou** [comment]
> > > I have this problem,too. Have you solved it? Thanks
> > 
> > 
> > Hey,I have solved this problem. Firstly, it is necessary to ensure the integrity of the dataset, and secondly, it is necessary to ensure that the path of the dataset is correct. ![Image](https://github.com/user-attachments/assets/9dfbd4df-da98-4ba5-935c-dfd191f727eb) ![Image](https://private-user-images.githubusercontent.com/136301478/435469937-6ffd22d1-bd05-4659-bf7a-06dc739e691b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NzQ3MjUsIm5iZiI6MTc2NDY3NDQyNSwicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM3LTZmZmQyMmQxLWJkMDUtNDY1OS1iZjdhLTA2ZGM3MzllNjkxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMlQxMTIwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTNmMWI5NzIyYjIwN2E5MzE3OWVhZDVkZWM2N2M2MTNhYTRjNGYzMGE1NDBiM2E2MDk1OTczZDg1ZTg2MzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LRoEHPx4rOWcaQfHuN2eZzG2SIu6lw-5u5uSxNM5xtI) ![Image](https://private-user-images.githubusercontent.com/136301478/435469938-91de06e8-0000-45c4-aac4-8321a74d0907.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NzQ3MjUsIm5iZiI6MTc2NDY3NDQyNSwicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM4LTkxZGUwNmU4LTAwMDAtNDVjNC1hYWM0LTgzMjFhNzRkMDkwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMlQxMTIwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NThlOGNhMzVlZmFhMWNjOGFhYzNlNTdkMDg0M2I3ZDRlMTdlOTAzNTI1ZDFlY2FlMjM4ZDNhYmY5YmJlMjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._QNJ6lz6GzlVy67dtKUr2rOWhPtM-iitdP56yv4fTak) ![Image](https://private-user-images.githubusercontent.com/136301478/435469939-9f4520eb-f2f7-4c2e-ac61-08dfe667b947.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ2NzQ3MjUsIm5iZiI6MTc2NDY3NDQyNSwicGF0aCI6Ii8xMzYzMDE0NzgvNDM1NDY5OTM5LTlmNDUyMGViLWYyZjctNGMyZS1hYzYxLTA4ZGZlNjY3Yjk0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMlQxMTIwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTIwNTQ4MGY4ZTdiMjllZmU5MGI5NGVlYzFmYmEzNzJlMjQ2OGQ3MjQ0ZGY1NDljZjUwN2IxMGYzYzg2YjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EFgmQ4ubrQ0EQhXrMtSkCcMN7JXbjvuNa42OPE_Yp_s)
> 
> i dont have this two json files ，can you tell me how to download，this is my e-mail [1491096801@qq.com](mailto:1491096801@qq.com)

Please follow the official readme. If there are missing files downloaded, it may be due to unstable network, as the dataset is too large.
