### ISSUE TITLE
There are some problems when "pip install -e .[habitat]"

### ISSUE THREAD

**Issue by dongxinfeng1** [bdaiinstitute/vlfm#36]
When I try to run "pip install -e .[habitat]", it show some problems:
"Cloning https://github.com/naokiyokoyama/frontier_exploration.git to /tmp/pip  install-a5f0snqu/frontier-exploration_e08d0e1395dd447cb7645c2064476bf7
  Running command git clone --filter=blob:none --quiet https://github.com/naokiy                                            okoyama/frontier_exploration.git /tmp/pip-install-a5f0snqu/frontier-exploration_                                          e08d0e1395dd447cb7645c2064476bf7
  error: RPC failed; curl 28 Failed to connect to github.com port 443: Connection timed out
  fatal: the remote end hung up unexpectedly
  error: subprocess-exited-with-error
  × git clone --filter=blob:none --quiet https://github.com/naokiyokoyama/fronti                                            er_exploration.git /tmp/pip-install-a5f0snqu/frontier-exploration_e08d0e1395dd44                                            7cb7645c2064476bf7 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  note: This error originates from a subprocess, and is likely not a problem wit                                            h pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/naokiyokoyama/frontier                                            _exploration.git /tmp/pip-install-a5f0snqu/frontier-exploration_e08d0e1395dd447c                                            b7645c2064476bf7 did not run successfully.
│ exit code: 128
╰─> See above for output.
".

Can you give me some advice? Thank you very much.

**Comment by drawtea1234** [comment]
I had the same problem and checking the network configuration solved it.
