### ISSUE TITLE
Cannot find SemExpITMPolicyV2, SemExpITMPolicyV3

### ISSUE THREAD

**Issue by JeffreyYH** [bdaiinstitute/vlfm#40]
I was trying to run the `eval.py` code in` vlfm/semexp_env `, in this line (14, `from vlfm.semexp_env.semexp_policy import SemExpITMPolicyV2, SemExpITMPolicyV3`) of `eval.py` file, I was not able to find `SemExpITMPolicyV2` and `SemExpITMPolicyV3` in this repo. Is there any way to provide these two files and also the training files?

**Comment by naokiyokoyama** [comment]
Seems like it was removed in a recent commit. Here is the latest commit before it was deleted:

https://github.com/bdaiinstitute/vlfm/blob/456ccef4a0a9ba2fdc863c0371e1e015298b3e30/vlfm/semexp_env/semexp_policy.py

**Comment by JeffreyYH** [comment]
Thank you for your reply! Even in this commit, the two policy classes
```
class SemExpITMPolicyV2(SemExpMixin, ITMPolicyV2):
    pass
class SemExpITMPolicyV3(SemExpMixin, ITMPolicyV3):
    pass
```
are all just empty.

In addition, in the repo I could not find `arguments` and `envs` either.
```
from arguments import get_args 
from envs import make_vec_envs
```

**Comment by naokiyokoyama** [comment]
They are not empty, they inherit an ITMPolicy combined with a mixin class.

Those imports assume that you have the repo fort Gibson ObjectNav installed https://github.com/devendrachaplot/Object-Goal-Navigation

**Comment by JeffreyYH** [comment]
Thank you! So shall I use the habitat version that Object-Goal-Navigation uses? Since I encountered many errors using the version from the installation instruction of the vlfm repo.

**Comment by naokiyokoyama** [comment]
Yes, you have to use the habitat version they use

**Comment by womeizhaol** [comment]
> Yes, you have to use the habitat version they use

Have you successfully downloaded and evaluated the Gibson dataset? Can you share your method or add a contact to discuss it?

**Comment by womeizhaol** [comment]
> Thank you! So shall I use the habitat version that Object-Goal-Navigation uses? Since I encountered many errors using the version from the installation instruction of the vlfm repo.

Have you successfully downloaded and evaluated the Gibson dataset? Can you share your method or add a contact to discuss it?

**Comment by womeizhaol** [comment]
> Thank you! So shall I use the habitat version that Object-Goal-Navigation uses? Since I encountered many errors using the version from the installation instruction of the vlfm repo.

I have the same question. Can you share your method or add a contact to discuss it?
