### ISSUE TITLE
The requirements on hardware

### ISSUE THREAD

**Issue by paobuliao** [bdaiinstitute/vlfm#42]
Would you mind providing your opinions on the choices of CPU and GPU, which would help me a lot in setting up a pc or choosing a suitable laptop. Thanks a lot!

**Comment by naokiyokoyama** [comment]
We used a laptop with a MaxQ GPU (mentioned in the paper)

**Comment by paobuliao** [comment]
Thank you for your response. You mentioned the use of the RTX 4090 Max-Q, which provides a general understanding of the system's requirements. However, it would be extremely helpful if you could also provide specific details on the time consumption for perception, reasoning, and decision-making processes.

My research interest is centered on the autonomous exploration of UAVs (Unmanned Aerial Vehicles). I am currently exploring the integration of scene understanding tools to enhance their capabilities in this domain. Given the constraint of limited computational resources typically available on drones, I am also looking into efficient algorithms and lightweight models that can provide robust scene interpretation without overwhelming the drone's onboard processing capabilities. Could you offer any suggestions or insights on this matter?
