### ISSUE TITLE
There are some problems when"python -m vlfm.run"

### ISSUE THREAD

**Issue by jingchuanDDD** [bdaiinstitute/vlfm#49]
When I run "python -m vlfm.run".it showed some problems:
2024-08-30 12:52:45,853 Initializing task ObjectNav-v1
2024-08-30 12:53:09,731 agent number of parameters: 0
  0%|                                                                                                                                                                           | 0/2000 [00:00<?, ?it/s]BLIP2ITMClient.cosine: (480, 640, 3), Seems like there is a tv ahead.
HTTPConnectionPool(host='localhost', port=12182): Max retries exceeded with url: /blip2itm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70a24c2c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='localhost', port=12182): Max retries exceeded with url: /blip2itm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70a24c2220>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='localhost', port=12182): Max retries exceeded with url: /blip2itm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70a24c23a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Are some problems for network configuration？Or the blip model is not downloaded locally？

**Comment by Xiaodao-chen** [comment]
did you solve it? I seem meet the same queation
![image](https://github.com/user-attachments/assets/39d16307-4119-4e80-9119-e39536b88ef2)

**Comment by jingchuanDDD** [comment]
The reason for this problem is that the  command **./scripts/launch_vlm_servers.sh**    failed to run

**Comment by itak04** [comment]
> ./scripts/launch_vlm_servers.sh

how to slove that

**Comment by jingchuanDDD** [comment]
@itak04 I execute the commands in **./scripts/launch_vlm_servers.sh** one by one and try to solve the error of each command

**Comment by Sellaris** [comment]
> [@itak04](https://github.com/itak04) I execute the commands in **./scripts/launch_vlm_servers.sh** one by one and try to solve the error of each command

Same problem .Is that because when"./scripts/launch_vlm_servers.sh"，blip2 downloaded goes wrong？Do I need clean the cache and rerun"./scripts/launch_vlm_servers.sh"？Or can u give me some instructions？THANK U.

**Comment by Sellaris** [comment]
After “./scripts/launch_vlm_servers.sh”，here's the prtsc of result,could anyone help me check ?![Image](https://github.com/user-attachments/assets/3cafb6d3-4a95-4cd8-ad10-240ce52d4bb8)

> 我逐个执行 **./scripts/launch_vlm_servers.sh** 中的命令，并尝试解决每个命令的错误

After “./scripts/launch_vlm_servers.sh”，here's the prtsc of result,could u help me check ?

![Image](https://github.com/user-attachments/assets/3212a3fe-f544-47ac-80a3-4758b330f57e)
