### ISSUE TITLE
Problem while doing pip install -e .[habitat]

### ISSUE THREAD

**Issue by bhagawan2017** [bdaiinstitute/vlfm#51]
I got the following error regarding torch version. How to solve this?
Thank you in advance. 

ERROR: Cannot install None, habitat-baselines, salesforce-lavis, vlfm and vlfm[habitat]==0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    vlfm 0.1 depends on torch>=1.10.0
    vlfm[habitat] 0.1 depends on torch>=1.10.0
    habitat-baselines 0.2.420230405 depends on torch>=1.3.1
    webdataset 0.1.40 depends on torch
    salesforce-lavis 1.0.2 depends on torch>=1.10.0
    fairscale 0.4.4 depends on torch>=1.8.0
    timm 0.4.12 depends on torch>=1.4
    groundingdino 0.1.0 depends on torch
    torchvision 0.10.1 depends on torch==1.9.1
    vlfm 0.1 depends on torch>=1.10.0
    vlfm[habitat] 0.1 depends on torch>=1.10.0
    habitat-baselines 0.2.420230405 depends on torch>=1.3.1
    webdataset 0.1.40 depends on torch
    salesforce-lavis 1.0.2 depends on torch>=1.10.0
    fairscale 0.4.4 depends on torch>=1.8.0
    timm 0.4.12 depends on torch>=1.4
    groundingdino 0.1.0 depends on torch
    torchvision 0.10.0 depends on torch==1.9.0
    vlfm 0.1 depends on torch>=1.10.0
    vlfm[habitat] 0.1 depends on torch>=1.10.0
    habitat-baselines 0.2.420230405 depends on torch>=1.3.1
    webdataset 0.1.40 depends on torch
    salesforce-lavis 1.0.2 depends on torch>=1.10.0
    fairscale 0.4.4 depends on torch>=1.8.0
    timm 0.4.12 depends on torch>=1.4
    groundingdino 0.1.0 depends on torch
    torchvision 0.9.1 depends on torch==1.8.1
    vlfm 0.1 depends on torch>=1.10.0
    vlfm[habitat] 0.1 depends on torch>=1.10.0
    habitat-baselines 0.2.420230405 depends on torch>=1.3.1
    webdataset 0.1.40 depends on torch
    salesforce-lavis 1.0.2 depends on torch>=1.10.0
    fairscale 0.4.4 depends on torch>=1.8.0
    timm 0.4.12 depends on torch>=1.4
    groundingdino 0.1.0 depends on torch
    torchvision 0.9.0 depends on torch==1.8.0
    vlfm 0.1 depends on torch>=1.10.0
    vlfm[habitat] 0.1 depends on torch>=1.10.0
    habitat-baselines 0.2.420230405 depends on torch>=1.3.1
    webdataset 0.1.40 depends on torch
    salesforce-lavis 1.0.2 depends on torch>=1.10.0
    fairscale 0.4.4 depends on torch>=1.8.0
    timm 0.4.12 depends on torch>=1.4
    groundingdino 0.1.0 depends on torch
    torchvision 0.8.2 depends on torch==1.7.1

**Comment by naokiyokoyama** [comment]
This should be fixed with the latest commit

**Comment by bhagawan2017** [comment]
Thank you for the reply. I still got following error. Please help.   
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blis 1.0.1 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
```

**Comment by flowers0** [comment]
> Thank you for the reply. I still got following error. Please help.
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> blis 1.0.1 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
> thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
> ```

Did your issue get resolved?
