### ISSUE TITLE
ERROR in python -m vlfm.run 

### ISSUE THREAD

**Issue by LebinLiang** [bdaiinstitute/vlfm#53]
AssertionError: ESP_CHECK failed: Missing (at least) one of scene dataset attributes, stage attributes, or dataset scene attributes for scene 'data/scene_datasets/hm3d/val/00853-5cdEh9F2hJL/5cdEh9F2hJL.basis.glb'.  Likely an invalid scene name
I had downloaded the HM3D and ran successfully before. But now there is a error happen

**Comment by lojol2327** [comment]
@LebinLiang Did you resolve the problem?
